---
title: "swissguesser leaderboard"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forcats)
#library(plotly)
library(ggplot2)

df <- read.csv("leaderboard.csv")#,
               #col_types = cols_only(user_name = col_character(),
              #                       user_handle = col_character(),
              #                       user_id = col_character(),
              #                       score = col_integer()))


df$user_handle <- as.factor(paste("@", df$user_handle, sep=""))
df$user_handle <- fct_reorder(df$user_handle, df$score, max, desc=TRUE)

```


This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.


```{r, echo=FALSE}
#fig <- plot_ly(
#  y = df$user_handle,
#  x = df$score,
#  name = "@swissguesser Leaderboard",
#  type = "bar",
#  orientation = "h"
#)
theme_geobeer <- function() {
  theme_minimal() +
    theme(
      text = element_text(color = "#22211d"),
      plot.title = element_text(lineheight=1, size = rel(2.1), face='bold'),
      plot.subtitle = element_text(size = rel(1.2), lineheight=1),
      plot.caption = element_text(size = rel(0.7)),
      plot.background = element_rect(fill = '#FAFAFA', colour=NA),
      legend.position = 'top',
      plot.margin = margin(10, 5, 5, 5, 'mm'))
}
theme_geobeer_horbar <- function() {
  theme_geobeer() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      axis.text.y = element_text(size = rel(1.3), colour='black'),
      axis.title.x = element_text(size = rel(1.1)))
}

fig <- ggplot(df, aes(x=user_handle, y=score)) +
  geom_bar(stat='identity', fill='#86D8FC') +
  theme_geobeer_horbar() +
  coord_flip() +
  labs(title='Title',
       subtitle='Subtitle',
       caption='caption',
       x='',
       y='\nScore')

fig

```

