name: Render leaderboard

on:
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  render:
    name: Render leaderboard
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install R dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("forcats")
          install.packages("plotly")
        shell: Rscript {0}
      - name: Render leaderboard
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: index.Rmd
          output_format: html_document
      - name: Push data to repo
        uses: github-actions-x/commit@v2.7
        with:
          push-branch: 'gh-pages'
          commit-message: 'Update leaderboard'
          force-add: 'true'
          name: autoupdate
